const packages = [
  {
    name: "Start Up Web Portal",
    price: "$11,999",
    services: [
      "Complete Custom Design & Development",
      "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Enterprise Portal (Any One)",
      "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
      "Unlimited Banner Designs",
      "Unlimited Stock Images",
      "User Signup Area",
      "Client/User Dashboard Area",
      "Custom Coding and Development",
      "Content Management System (Custom)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Shopping Cart Integration (Optional)",
      "Web Traffic Analytics Integration",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar for Easy Search",
      "Live Feeds of Social Networks integration (Optional)",
      "Search Engine Submission",
      "Module-wise Architecture",
      "Extensive Admin Panel",
      "Award Winning Team of Expert Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "WEB PORTAL PLUS",
    price: "$19,999",
    services: [
      "Complete Custom Design & Development",
      "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
      "Unique, User Friendly, Interactive, Dynamic, High End UI Design",
      "Unlimited Banner Designs",
      "Interactive Sliding Banners",
      "Special Hover Effects",
      "Unlimited Stock Images",
      "User Signup Area",
      "Client/User Dashboard Area",
      "Custom Coding and Development",
      "Content Management System (Custom)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Shopping Cart Integration (Optional)",
      "Complete Database Creation",
      "Signup Automated Email Authentication",
      "Web Traffic Analytics Integration",
      "3rd Party API Integrations",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar for Easy Search",
      "Live Feeds of Social Networks integration (Optional)",
      "Search Engine Submission",
      "Module-wise Architecture",
      "Extensive Admin Panel",
      "Award Winning Team of Expert Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];
export default packages;
