 const packages = [
  {
    name: "The Executive",
    price: "$899",
    services: [
      "Whiteboard Video",
      "Custom Artwork; No Preused Images",
      "Professional Script Writing",
      "Unlimited Storyboard Revisions",
      "Professional Voice-Over",
      "Background Music",
      "Exotic Animations",
      "HD Video Production",
      "Get More",
      "Add video script $120/minute",
      "30 seconds Video Duration",
      "*(Yes, you can ask for more!)",
      "More Features",
      "100% Satisfaction Guarentee",
      "Dedicated Account Executive",
      "24 X 7 Customer Support",
      "Moneyback Guarantee",
    ],
  },
  {
    name: "The Manager",
    price: "$1599",
    services: [
      "2D Animation/Motion Graphics",
      "Custom Artwork; No Preused Images",
      "Professional Script Writing",
      "Unlimited Storyboard Revisions",
      "Professional Voice-Over",
      "Background Music",
      "Exotic Animations",
      "Get More",
      "HD Video Production",
      "30 seconds Video Duration",
      "*(Yes, you can ask for more!)",
      "More Features",
      "100% Satisfaction Guarantee",
      "Dedicated Account Executive",
      "24 X 7 Customer Support",
      "Moneyback Guarantee",
    ],
  },
  {
    name: "The Boss",
    price: "$2999",
    services: [
      "Custom Character Illustration",
      "Custom Artwork; No Preused Images",
      "Professional Script Writing",
      "Unlimited Storyboard Revisions",
      "Professional Voice-Over",
      "Background Music",
      "Exotic Animations",
      "Get More",
      "HD Video Production",
      "30 seconds Video Duration",
      "*(Yes, you can ask for more!)",
      "More Features",
      "100% Satisfaction Guarantee",
      "Dedicated Account Executive",
      "24 X 7 Customer Support",
      "Moneyback Guarantee",
    ],
  },
];
export default packages