const packages = [
  {
    name: "BRONZE",
    price: "$397",
    services: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "3 Posts per Week",
      "1 Facebook Event",
      "Monthly Reporting",
      "Ad",
    ],
  },
  {
    name: "SILVER ",
    price: "$597",
    services: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "4 Posts per Week",
      "2 Facebook Events",
      "Monthly Reporting",
      "Ad Spend - Up to $65",
    ],
  },
  {
    name: "GOLD ",
    price: "$979",
    services: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "5 Posts per Week",
      "2 Facebook Events",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad Spend - Up to $120",
    ],
  },
  {
    name: "PLATINUM ",
    price: "$1497",
    services: [
      "Optimize FB Page",
      "1 Social Cover + Holiday Covers",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "6 Posts per Week",
      "2 Facebook Events",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad Spend - Up to $170",
    ],
  },
];
export default packages;
