const packages = [
  {
    name: "Basic Website",
    price: "$499",
    services: [
      "3 Page Website",
      "Custom Layout Design",
      "Contact/Query Form",
      "1 Banner Design",
      "2 Stock Photos",
      "FREE Favicon Design",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    name: "Start Up Website",
    price: "$899",
    services: [
      "5 Page Website",
      "Custom Layout Design",
      "Contact/Query Form",
      "3 Banner Designs",
      "5 Stock Photos",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap",
      "Unlimited Revisions",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    name: "Professional Website",
    price: "$1499",
    services: [
      "Up to 10 Unique Pages Website",
      "CMS /Admin Panel Integration",
      "5+ Stock Photos & Banner Designs",
      "FREE Social Media Integration",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap",
      "Unlimited Revisions",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Custom, Interactive & Dynamic Web Design",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    name: "E-Commerce Website",
    price: "$2999",
    services: [
      "Custom Ecommerce Website",
      "Up to 200 Products",
      "CMS /Admin Panel Integration",
      "Fully Mobile Responsive",
      "Shopping Cart Integration",
      "Payment Gateway Integration",
      "Product Listing & Management",
      "Order Management & Tracking",
      "Banner Designs",
      "Unlimited Revisions",
      "FREE Social Media Integration",
      "FREE Favicon Design",
      "FREE Google Friendly Sitemap Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    name: "Corporate Website",
    price: "$3999",
    services: [
      "Up to 15 Unique Pages Website",
      "Custom Made, Interactive & Dynamic Design",
      "Customized WordPress or PHP Development",
      "Fully Mobile Responsive",
      "Interactive Sliding Banners",
      "Up to 10 Custom Made Banner Designs",
      "10 Stock Images",
      "Unlimited Revisions",
      "Content Management System",
      "Online Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Up to 15 Professional Email ID’s",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    name: "Platinum Website",
    price: "$6999",
    services: [
      "Up to 20 Unique Pages Website",
      "Custom Made, Interactive, Dynamic & High-End Design",
      "Customized WordPress or PHP Development",
      "Fully Mobile Responsive",
      "Interactive Sliding Banners",
      "Up to 15 Custom Made Banner Designs",
      "15 Stock Images",
      "Unlimited Revisions",
      "Content Management System",
      "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Up to 15 Professional Email ID’s",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Industry specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
];
export default packages;
