import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import Footer from "./components/Footer";
import Copyrights from "./components/Copyrights";
import Leadform from "./components/Leadform";
import Testimonial from "./Home/Testimonial";
import TestimonialCrousel from "./components/TestimonialCrousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gojozeal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
          />
        </head>
      </head>
      <body className={` ${inter.className}`}>
        <Header />
        {children}
      </body>
      <Leadform />
      <Footer />
      <Copyrights />
    </html>
  );
}
