const packages = [
  {
    name: "LOGO SPECIAL",
    price: "$59",
    services: [
      "4 Original Logo Concepts",
      "2 Dedicated Logo Designer",
      "4 Revisions",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG Only",
      "24 - 48 Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    name: "The Plus",
    price: "$199",
    services: [
      "12 Original Logo Concepts",
      "4 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Email Signature Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
      "24/7 Support (Email, Chat, Call, SMS, Whatsapp)",
    ],
  },
  {
    name: "LOGO PLATINUM",
    price: "$399",
    services: [
      "Unlimited Original Logo Concepts",
      "8 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "500 Business Cards",
      "Email Signature Design",
      "Social Media Designs (Facebook, Twitter, Instagram)",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    name: "THE BOSS",
    price: "$599",
    services: [
      "3D/Mascot/Animated Logo",
      "Unlimited Original Logo Concepts",
      "8 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "500 Business Cards",
      "Email Signature Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    name: "LOGO INFINITE",
    price: "$1259",
    services: [
      "Unlimited Original Logo Concepts",
      "8 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "5 Page Informative Website",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Brand Book",
      "500 Business Cards",
      "500 Letterheads",
      "Email Signature Design",
      "Social Media Designs (Facebook, Twitter, Instagram)",
      "2 Sided Flyer OR Bi-Fold Brochure Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    name: "LOGO COMBO",
    price: "$1499",
    services: [
      "Unlimited Original Logo Concepts",
      "12 Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Ecommerce Website",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Brand Book",
      "500 Business Cards",
      "500 Letterheads",
      "Email Signature Design",
      "Social Media Designs (Facebook, Twitter, Instagram)",
      "2 Sided Flyer OR Bi-Fold Brochure Design",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
      "24 - 48 Hours Turn Around Time",
      "MORE FEATURES",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
];
export default packages;
