const packages = [
  {
    name: "BRANDING STARTUP",
    price: "$1999",
    services: [
      "Logo Design",
      "6 Unique Logo Concepts",
      "FREE Icon",
      "FREE Grayscale Copy",
      "Unlimited Revisions",
      "100% Ownership Right",
      "AI, PSD, EPS, GIF, BMP, JPEG, PNG Formats",
      "Print Media",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Website Design",
      "10 Pages Custom Business Website",
      "Free 12 Month Hosting & Domain Registration",
      "Mobile Responsive",
      "FREE Google Friendly Sitemap Search Engine Submission",
      "Complete W3C Certified HTML",
      "Complete Deployment",
    ],
  },
  {
    name: "Branding Plus",
    price: "$2999",
    services: [
      "Logo Design",
      "12 Unique Logo Concepts",
      "FREE Icon",
      "FREE Grayscale Copy",
      "Unlimited Revisions",
      "100% Ownership Right",
      "AI, PSD, EPS, GIF, BMP, JPEG, PNG Formats",
      "Print Material",
      "Stationery Design(Business Card,Letterhead,Envelope)",
      "Flyer Design / Label Design",
      "Website Design",
      "Custom Ecommerce Website",
      "Up to 200 Products",
      "CMS /Admin Panel Integration",
      "Fully Mobile Responsive",
      "Shopping Cart Integration",
      "Payment Gateway Integration",
      "Responsive Design (Mobile Compatible)",
      "Complete Deployment",
      "Social Media Design",
      "Facebook Fanpage Splash Page + Cover Photo",
    ],
  },
];

export default packages;
