export const logoItems = [
  
  "3 Page Website",
  "Custom Layout Design",
  "Contact/Query Form",
  "1 Banner Design",
  "2 Stock Photos",
  "FREE Favicon Design",
  "Cross Browser Compatible",
  "Complete W3C Certified HTML",
  "Website Initial Concepts in 48 Hours",
  "Complete Design & Deployment",
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
  "Value Added Services",
  "Mobile Responsive will be Additional $200*",
  "CMS will be Additional $250*",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];
export const logoSpecialPackage = [
  "Free Icon Design",
  "Formats: JPEG Only",
  "24 - 48 Hours Turn Around Time",
  "MORE FEATURES",
  "100% Satisfaction",
  "100% Ownership Rights",
  "Money Back Guarantee",
  "Dedicated Account Manager",
];

export const logoPlusPackage = [
  "12 Original Logo Concepts",
  "4 Dedicated Logo Designer (Industry Specific)",
  "Unlimited Revisions",
  "Stationery Design (Business Card, Letterhead, Envelope)",
  "Email Signature Design",
  "With Grey Scale Format",
  "Free Icon Design",
  "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
  "24 - 48 Hours Turn Around Time",
  "MORE FEATURES",
  "100% Satisfaction",
  "100% Ownership Rights",
  "Money Back Guarantee",
  "Dedicated Account Manager",
  "24/7 Support (Email, Chat, Call, SMS, Whatsapp)",
];

export const logoPlatiumPackage = [
  "Unlimited Original Logo Concepts",
  "8 Dedicated Logo Designer (Industry Specific)",
  "Unlimited Revisions",
  "Stationery Design (Business Card, Letterhead, Envelope)",
  "500 Business Cards",
  "Email Signature Design",
  "Social Media Designs (Facebook, Twitter, Instagram)",
  "With Grey Scale Format",
  "Free Icon Design",
  "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
  "24 - 48 Hours Turn Around Time",
  "MORE FEATURES",
  "100% Satisfaction",
  "100% Ownership Rights",
  "Money Back Guarantee",
  "Dedicated Account Manager",
];

export const logoBossPackage = [
  "    3D/Mascot/Animated Logo",
  "Unlimited Original Logo Concepts",
  "8 Dedicated Logo Designer (Industry Specific)",
  "Unlimited Revisions",
  "Stationery Design (Business Card, Letterhead, Envelope)",
  "500 Business Cards",
  "Email Signature Design",
  "With Grey Scale Format",
  "Free Icon Design",
  "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
  "24 - 48 Hours Turn Around Time",
  "MORE FEATURES",
];

export const logoInfinitePackage = [
  "Unlimited Original Logo Concepts",
  "8 Dedicated Logo Designer (Industry Specific)",
  "Unlimited Revisions",
  "5 Page imformative Website",
  "Stationery Design (Business Card, Letterhead, Envelope)",
  "Brand Book",
  "500 Business Cards",
  "500 Letterheads",
  "Email Signature Design",
  "Social Media Designs (Facebook, Twitter, Instagram)",
  "2 Sided Flyer OR Bi-Fold Brochure Design",
  "With Grey Scale Format",
  "Free Icon Design",
  "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
  "24 - 48 Hours Turn Around Time",
  "MORE FEATURES",
  "100% Satisfaction",
  "100% Ownership Rights",
  "Money Back Guarantee",
  "Dedicated Account Manager",
];

export const logoComboPackage = [
  "Unlimited Original Logo Concepts",
  "12 Dedicated Logo Designer (Industry Specific)",
  "Unlimited Revisions",
  "Ecommerce Website",
  "Stationery Design (Business Card, Letterhead, Envelope)",
  "Brand Book",
  "500 Business Cards",
  "500 Letterheads",
  "Email Signature Design",
  "Social Media Designs (Facebook, Twitter, Instagram)",
  "2 Sided Flyer OR Bi-Fold Brochure Design",
  "With Grey Scale Format",
  "Free Icon Design",
  "Formats: JPEG, PSD, EPS, AI, PNG, TIFF, SVG",
  "24 - 48 Hours Turn Around Time",
  "MORE FEATURES",
  "100% Satisfaction",
  "100% Ownership Rights",
  "Money Back Guarantee",
  "Dedicated Account Manager",
];

// Website Items

export const basicWebsite = [
  "3 Page Website",
  "Custom Layout Design",
  "Contact/Query Form",
  "1 Banner Design",
  "2 Stock Photos",
  "FREE Favicon Design",
  "Cross Browser Compatible",
  "Complete W3C Certified HTML",
  "Website Initial Concepts in 48 Hours",
  "Complete Design & Deployment",
  "Complete Source Files ",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
  "Value Added Services",
  "Mobile Responsive will be Additional $200*",
  "CMS will be Additional $250*",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];

export const strartupWebsite = [
  "5 Page Website",
  "Custom Layout Design",
  "Contact/Query Form",
  "3 Banner Designs",
  "5 Stock Photos",
  "FREE Favicon Design",
  "FREE Google Friendly Sitemap",
  "Unlimited Revisions",
  "Complete W3C Certified HTML",
  "Website Initial Concepts in 48 Hours",
  "Complete Design & Deployment",
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee ",
  "100% Money Back Guarantee",
  "Value Added Services",
  "Mobile Responsive will be Additional $200*",
  "CMS will be Additional $250*",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];

export const professionalWebsite = [
  " Up to 10 Unique Pages Website",
  "MS /Admin Panel Integration",
  "5+ Stock Photos & Banner Designs",
  "FREE Social Media Integration",
  "FREE Favicon Design",
  "FREE Google Friendly Sitemap",
  "Unlimited Revisions",
  "Cross Browser Compatible",
  "Complete W3C Certified HTML",
  "Website Initial Concepts in 48 Hours",
  "Complete Design & Deployment",
  "Custom, Interactive & Dynamic Web Design",
  "Industry specified Team of Expert Designers and Developers",
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
  "Value Added Services",
  "Mobile Responsive will be Additional $200*",
  "CMS will be Additional $250*",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];

export const ecomerceWebsite = [
  "Custom Ecommerce Website",
  "Up to 200 Products",
  "CMS /Admin Panel Integration",
  "Fully Mobile Responsive",
  "Shopping Cart Integration",
  "Payment Gateway Integration",
  "Product Listing & Management",
  "Order Management & Tracking",
  "Banner Designs",
  "Unlimited Revisions",
  "FREE Social Media Integration",
  "FREE Favicon Design",
  "FREE Google Friendly Sitemap Search Engine Submission",
  "Complete W3C Certified HTML",
  "Industry specified Team of Expert Designers and Developers",
  "Complete Deployment",
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];

export const corporateWebsite = [
  "Up to 15 Unique Pages Website",
  "Custom Made, Interactive & Dynamic Design",
  "Customized WordPress or PHP Development",
  "Fully Mobile Responsive",
  "Interactive Sliding Banners",
  "Up to 10 Custom Made Banner Designs",
  "10 Stock Images",
  "Unlimited Revisions",
  "Content Management System",
  "Online Signup Area (For Newsletters, Offers etc.)",
  "Search Bar",
  "Live Feeds of Social Networks integration (Optional)",
  "Up to 15 Professional Email ID’s",
  "Google Friendly Sitemap",
  "Search Engine Submission",
  "Cross Browser Compatible",
  "Complete W3C Certified HTML",
  "Industry specified Team of Expert Designers and Developers",
  "Complete Deployment",
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];

export const platinuimWebsite = [
  "Up to 20 Unique Pages Website",
  "Custom Made, Interactive, Dynamic & High-End Design",
  "Customized WordPress or PHP Development",
  "Fully Mobile Responsive",
  "Interactive Sliding Banners",
  "Up to 15 Custom Made Banner Designs",
  "15 Stock Images",
  "Unlimited Revisions",
  "Content Management System",
  "Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)",
  "Online Payment Integration (Optional)",
  "Multi Lingual (Optional)",
  "Custom Dynamic Forms (Optional)",
  "Signup Area (For Newsletters, Offers etc.)",
  "Search Bar",
  "Live Feeds of Social Networks integration (Optional)",
  "Up to 15 Professional Email ID’s",
  "Google Friendly Sitemap",
  "Search Engine Submission",
  "Cross Browser Compatible",
  "Complete W3C Certified HTML",
  "Industry specified Team of Expert Designers and Developers",
  "Complete Deployment",
  "Complete Source Files",
  "Dedicated Project Manager",
  "100% Ownership Rights",
  "100% Satisfaction Guarantee",
  "100% Money Back Guarantee",
  "*NO MONTHLY OR ANY HIDDEN FEE*",
];

export const basicSeo = [
  "10 Keywords Optimization",
  "4 Keywords in top 10",
  "Search Engine Submissions",
  "2 Blogs Writing",
  "4 Blog Posting Links",
  "10 Blogs Social Bookmarking Links",
  "1 Press Release Writing",
  "2 Press Release Links",
];

export const standardSeo = [
  "25 Keywords Optimization",
  "10 Keywords in top 10",
  "Search Engine Submissions",
  "6 Blogs Writing",
  "12 Blog Posting Links",
  "10 Blogs Social Bookmarking Links",
  "2 Press Release Writing",
  "4 Press Release Links",
];

export const professionalSeo = [
  "50 Keywords Optimization",
  "20 Keywords in top 10",
  "Search Engine Submissions",
  "14 Blogs Writing",
  "28 Blog Posting Links",
  "30 Blogs Social Bookmarking Links",
  "4 Press Release Writing",
  "8 Press Release Links",
  "4 Guest Blogging Links",
];

export const enterpriseSeo = [
  "100 Keywords Optimization",
  "40 Keywords in top 10",
  "Search Engine Submissions",
  "30 Blogs Writing",
  "28 Blog Posting Links",
  "40 Blogs Social Bookmarking Links",
  "8 Press Release Writing",
  "8 Press Release Links",
  "8 Guest Blogging Links",
];
